import json
from datetime import datetime
from researchmind.core.agent import PaperAnalysisResult


class PaperExporter:
    @staticmethod
    def to_markdown(result: PaperAnalysisResult) -> str:
        date_str = datetime.fromtimestamp(result.timestamp).strftime("%Y-%m-%d %H:%M:%S")
        meta = result.metadata or {}
        authors_str = ", ".join(meta.get("authors", [])) if meta.get("authors") else "Unknown"

        lines = [
            f"# Research Analysis: {result.paper_title}",
            "",
            f"> **Generated by**: ResearchMind AI (`{result.model_used}`) on {date_str}  ",
            f"> **Authors**: {authors_str} | **Pages**: {meta.get('num_pages', 'N/A')} | **arXiv**: {meta.get('arxiv_id', 'N/A')}",
            "",
            "---",
            "",
            "## Table of Contents",
        ]

        for key, section in result.sections.items():
            anchor = section.title.lower().replace(" ", "-").replace("&", "").replace("/", "")
            lines.append(f"- [{section.title}](#{anchor})")

        lines.extend(["", "---", ""])

        for key, section in result.sections.items():
            lines.append(f"## {section.title}")
            lines.append(f"*Analysis completed in {section.generation_time_s}s*")
            lines.append("")
            lines.append(section.content.strip())
            lines.append("")
            lines.append("---")
            lines.append("")

        return "\n".join(lines)

    @staticmethod
    def to_json(result: PaperAnalysisResult, indent: int = 2) -> str:
        return json.dumps(result.to_dict(), indent=indent)

    @staticmethod
    def to_html(result: PaperAnalysisResult) -> str:
        md_content = PaperExporter.to_markdown(result)
        date_str = datetime.fromtimestamp(result.timestamp).strftime("%B %d, %Y")

        html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{result.paper_title} - ResearchMind Report</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css">
  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js"
    onload="renderMathInElement(document.body, {{
      delimiters: [
        {{left: '$$', right: '$$', display: true}},
        {{left: '$', right: '$', display: false}}
      ]
    }});"></script>
  <style>
    @media print {{
      .no-print {{ display: none !important; }}
      body {{ font-size: 12pt; line-height: 1.5; }}
    }}
    .prose pre {{ background-color: #1e293b; color: #f8fafc; padding: 1rem; border-radius: 0.5rem; overflow-x: auto; }}
    .prose code {{ font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; }}
    .prose table {{ width: 100%; border-collapse: collapse; margin-top: 1rem; margin-bottom: 1rem; }}
    .prose th, .prose td {{ border: 1px solid #e2e8f0; padding: 0.5rem 0.75rem; text-align: left; }}
    .prose th {{ background-color: #f8fafc; font-weight: 600; }}
  </style>
</head>
<body class="bg-slate-50 text-slate-900 min-h-screen">
  <div class="max-w-4xl mx-auto py-10 px-6">
    <div class="flex justify-between items-center mb-8 no-print border-b border-slate-200 pb-4">
      <div class="flex items-center space-x-2">
        <span class="text-2xl font-bold bg-gradient-to-r from-indigo-600 to-violet-600 bg-clip-text text-transparent">ResearchMind AI</span>
        <span class="text-xs bg-indigo-100 text-indigo-700 px-2 py-0.5 rounded-full font-medium">Report</span>
      </div>
      <button onclick="window.print()" class="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg transition-colors">
        Print / Save PDF
      </button>
    </div>

    <main id="content" class="bg-white rounded-xl shadow-sm border border-slate-200 p-8 sm:p-12 prose prose-slate max-w-none">
      <div id="raw-markdown" style="display:none;">{md_content}</div>
    </main>
    
    <footer class="mt-8 text-center text-xs text-slate-400 no-print">
      Generated automatically by ResearchMind AI using {result.model_used}
    </footer>
  </div>

  <script>
    const md = document.getElementById('raw-markdown').innerText;
    document.getElementById('content').innerHTML = marked.parse(md);
  </script>
</body>
</html>"""
        return html_template

